pytest-dev/pytest-factoryboy

- CHANGES.rst
- pytest_factoryboy/__init__.py
- pytest_factoryboy/fixture.py
- setup.py
- tests/test_factory_fixtures.py
- refactoring of the fixture function compilation
- related factory fix
> Creation of the fixture functions and related factory test fix

- CHANGES.rst
- pytest_factoryboy/__init__.py
- pytest_factoryboy/fixture.py
- tests/test_postgen_dependencies.py
Doesn't fix circular dependencies for the pytest-bdd yet, but those situations have to be solved via the step hooks. I guess if we reset the factoryboy request "initialized" property on every step and call evaluate in the end of the every step it will solve it.
For now it should solve the basic problem when getfuncargvalue can't find the model fixture when computed instantly together with the post-generation declarations.
> Fixes post-generation declarations when called via the getfuncargvalue

- AUTHORS.rst
- CHANGES.rst
- README.rst
- pytest_factoryboy/__init__.py
- pytest_factoryboy/fixture.py
- pytest_factoryboy/plugin.py
- tests/test_circular.py
- tests/test_postgen_dependencies.py
It seems to be possible to detect cyclic dependencies by traversing pytest fixturedefs.
This way if RelatedFactory declarations would be executed before post_generation declarations with some sort of heuristics it might work automatically without configuring post generation dependencies. Which is a hard problem as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/26)
> Remove post deps

- .travis.yml
- pytest_factoryboy/fixture.py
- pytest_factoryboy/plugin.py
- setup.py
- tox.ini
SubRequest objects do not have any attribute '_fixturedefs' but an attribute '_fixture_defs' (see https://github.com/pytest-dev/pytest/blob/master/_pytest/fixtures.py#L588).
Pull request for this issue: https://github.com/pytest-dev/pytest-factoryboy/issues/29
(Solve a regression introduced in this commit : d5a37f5)
> replace request._fixturedefs by request._fixture_defs, solve issue #29

- README.rst
I think AuthorFactory is wrong here, found this slightly confusing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/35)
> Correct factory in the last LazyFixture example

- setup.py
Until compatibility is fixed PRs should not fail because of it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/51)
> setup.py: pin factory_boy<2.9

- tox.ini
This allows to pass in arguments for pytest, e.g. `-k` or the test
path(s).
This also removes the pytest_factoryboy dir, since it does not contain
any tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/45)
> tox.ini: use {posargs} in pytest command

- .gitignore
- CHANGES.rst
- pytest_factoryboy/__init__.py
- pytest_factoryboy/fixture.py
- pytest_factoryboy/plugin.py
- setup.py
- tests/test_attributes_field.py
- tests/test_factory_fixtures.py
- tests/test_postgen_dependencies.py
Both pytest and factory_boy have heavily changed their internals.
Therefore there's a decision to do a major release 2.0.0 to be compatible with the latest library versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/57)
> V2: Support for pytest>=3.3.2 and factory_boy>=2.10.0

- pytest_factoryboy/plugin.py
- tests/test_postgen_dependencies.py
Fixes #68
getfixturevalue already exists since pytest version [3.0.0](https://docs.pytest.org/en/latest/changelog.html#id329)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/62)
> Fix warning `use of getfuncargvalue is deprecated, use getfixturevalue`

- pytest_factoryboy/fixture.py
- setup.py
This avoids deprecation warning as inspect.getargspec() is deprecated in Python 3.5+
See https://github.com/pytest-dev/pytest-bdd/pull/164 for a similar fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/70)
> Use inspect.signature() to avoid deprecation warning

- .travis.yml
- AUTHORS.rst
- CHANGES.rst
- setup.py
- tox.ini
Python 3.4 is EOL and no longer receiving security updates (or any updates) from the core Python team.
Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.4 | 2014-03-16 | 2019-03-16
Source: https://en.wikipedia.org/wiki/CPython#Version_history
It's also little used. Here's the pip installs for pytest-factoryboy from PyPI for September 2019:
| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  45.44% |    17,493 |
| 3.6      |  31.35% |    12,071 |
| 2.7      |  17.05% |     6,563 |
| 3.5      |   4.80% |     1,847 |
| null     |   1.20% |       462 |
| 3.4      |   0.16% |        60 |
| 2.6      |   0.01% |         3 |
| Total    |         |    38,499 |
Date range: 2019-09-01 - 2019-09-30
Source: `pip …
> Drop support for old Python and pytest

- .travis.yml
- CHANGES.rst
- pyproject.toml
- setup.py
- tox.ini
This PR:
+ adds Python 3.9 to supported python versions (add classifiers to `setup.py` and run tests)
+ removes python 3.5 from supported python versions
+ sync `pytest` versions supported by `pytest-factoryboy` with these officially maintained by `pytest-dev` team (I get versions from branch list of `pytest` repo)
+ remove invalid (or no longer used/needed) `pep8maxlinelength` pytest's ini option
What do you think about dropping support for python 2?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/104)
> update supported python and pytest versions

- docs/index.rst
It's already on the left menu, no need to have a long table of contents with all the changelog in the initial text.
> Remove Table of Contents from the doc

- pytest_factoryboy/codegen.py
The generated filenames are like foo_1, foo_1_2, foo_1_2_3. That's a bug, they should be: foo_1, foo_2, foo_3.
> Fix generated filenames

- CHANGES.rst
- pytest_factoryboy/fixture.py
- tests/test_postgen_dependencies.py
The `result` parameter was not receiving the values of the evaluated postgens correctly (they were always None).
Now the `result` parameter is populated correctly.
Checklist:
> Fix _after_postgeneration results parameter

- CHANGES.rst
- pytest_factoryboy/fixture.py
- tests/test_namespaces.py
Fixes https://github.com/pytest-dev/pytest-factoryboy/issues/140
TODO:
> Allow factories to be registered within classes without polluting outer namespace.

- pyproject.toml
- pytest_factoryboy/codegen.py
- pytest_factoryboy/fixture.py
- tests/test_lazy_fixture.py
- tests/test_postgen_dependencies.py
Refactor the generation of the FixtureDefs for a factory.
The code is now way more simple, and the big chunk of code that creates the FixtureDef is extracted into its own function.
A side effect of this change is that we legislate the usage of LazyFixture in a Factory declaration. For example, this code is now fully supported:
```python
@pytest.fixture
def name():
return "John"
@register
class UserFactory(factory.Factory):
username = LazyFixture("name")
def test_name(user):
assert user.name == "John"
```
This can be useful for small factories that are needed just for individual test modules, and that won't ever be used without a pytest context.
> Refactor FixtureDef generation logic

- CHANGES.rst
- README.rst
- poetry.lock
- pyproject.toml
- pytest_factoryboy/fixture.py
- tests/compat.py
- tests/conftest.py
- tests/test_factory_name.py
Often I make factories for a `dict`, and it's getting annoying that by default the fixture name is `"dict"`.
This PR changes it to use the factory name to determine the fixture name.
For example, this factory
```python
@register
class HTTPHeadersFactory(factory.Factory):
class Meta:
model = dict
Authorization = "Basic Zm9vOmJhcg=="
```
will now register a fixture called `http_headers`, instead of `dict`.
> Determine the fixture name using the factory name, rather than the model

- CHANGES.rst
- pytest_factoryboy/fixture.py
- tests/test_postgen_dependencies.py
Partially fixes https://github.com/pytest-dev/pytest-factoryboy/issues/156.
> Fix _after_postgeneration being invoked twice

- CHANGES.rst
- README.rst
- poetry.lock
- pyproject.toml
- pytest_factoryboy/__init__.py
- pytest_factoryboy/fixture.py
- tests/compat.py
- tests/conftest.py
- tests/test_model_name.py
Implementing the idea previously described in https://github.com/pytest-dev/pytest-factoryboy/pull/163#issuecomment-1146873731.
We add a helper function, `named_model`, that makes sure the user uses a model with a specific name, rather than a generic dict, list, etc.
This way we avoid problems that arises when SubFactory and RelatedFactory are used with factories for generic models. See the tests for examples.
> Add `named_model` function and raise warning for factories using generic models

- CHANGES.rst
- pytest_factoryboy/fixture.py
Having the `caller_locals` in the scope caused the stack traces to be very long.
Now we wrap `caller_locals` in a Box object, so that it's representation will be 1 line instead of 100.
> Slim stack traces

- README.rst
Book not have a `name` but a `title`.
> docs(readme): fix typo in readme

- README.rst
* Remove highlight from the "Factory fixture" section, since it's probably the least important
* Update example of `other_book__author` to be more clear
> Update README.rst examples

- CHANGES.rst
- poetry.lock
- pyproject.toml
- pytest_factoryboy/compat.py
- pytest_factoryboy/plugin.py
The signature of this (private) function will change in the upcoming pytest 8.1 release:
https://github.com/pytest-dev/pytest/pull/11785
I verified that all tests pass when run against pytest main.
> Adapt to `getfixturedefs` change in pytest 8.1

- README.rst
fixed the usage example of named_model since it is incorrect comparing to the implementation. 
- doc: https://pytest-factoryboy.readthedocs.io/en/stable/index.html#generic-container-classes-as-models
- implementation: https://github.com/pytest-dev/pytest-factoryboy/blob/ca5bb0971e7fa393ad4e999560d2ca3da046c85e/pytest_factoryboy/fixture.py#L73C1-L75C40
> Fix example doc of named_model

- README.rst
The parameters in the docs don't match the implementation where the `name` is the first argument.
```py
def named_model(model_cls: type[T], name: str) -> type[T]:
"""Return a model class with a given name."""
return type(name, (model_cls,), {})
```
> The parameter order of `named_model` in docs does not match the implementation

- pytest_factoryboy/compat.py
- pytest_factoryboy/fixture.py
- pytest_factoryboy/fixturegen.py
Fix https://github.com/pytest-dev/pytest-factoryboy/issues/232
Checklist:
> Fix pytest 8.4 compatibility
